/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Boundingbox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoundingboxTests
    {
        // TODO uncomment below to declare an instance variable for Boundingbox
        //private Boundingbox instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Boundingbox
            //instance = new Boundingbox();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Boundingbox
        /// </summary>
        [Test]
        public void BoundingboxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Boundingbox
            //Assert.IsInstanceOfType<Boundingbox> (instance, "variable 'instance' is a Boundingbox");
        }


        /// <summary>
        /// Test the property 'EndPosition'
        /// </summary>
        [Test]
        public void EndPositionTest()
        {
            // TODO unit test for the property 'EndPosition'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'StartPosition'
        /// </summary>
        [Test]
        public void StartPositionTest()
        {
            // TODO unit test for the property 'StartPosition'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'XLocation'
        /// </summary>
        [Test]
        public void XLocationTest()
        {
            // TODO unit test for the property 'XLocation'
        }
        /// <summary>
        /// Test the property 'YLocation'
        /// </summary>
        [Test]
        public void YLocationTest()
        {
            // TODO unit test for the property 'YLocation'
        }

    }

}
