/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CloudStorageConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudStorageConfigTests
    {
        // TODO uncomment below to declare an instance variable for CloudStorageConfig
        //private CloudStorageConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CloudStorageConfig
            //instance = new CloudStorageConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CloudStorageConfig
        /// </summary>
        [Test]
        public void CloudStorageConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CloudStorageConfig
            //Assert.IsInstanceOfType<CloudStorageConfig> (instance, "variable 'instance' is a CloudStorageConfig");
        }


        /// <summary>
        /// Test the property 'GoogleStorageConfig'
        /// </summary>
        [Test]
        public void GoogleStorageConfigTest()
        {
            // TODO unit test for the property 'GoogleStorageConfig'
        }
        /// <summary>
        /// Test the property 'BlobStorageConfig'
        /// </summary>
        [Test]
        public void BlobStorageConfigTest()
        {
            // TODO unit test for the property 'BlobStorageConfig'
        }
        /// <summary>
        /// Test the property 'S3Config'
        /// </summary>
        [Test]
        public void S3ConfigTest()
        {
            // TODO unit test for the property 'S3Config'
        }

    }

}
