/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DBConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DBConfigTests
    {
        // TODO uncomment below to declare an instance variable for DBConfig
        //private DBConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DBConfig
            //instance = new DBConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DBConfig
        /// </summary>
        [Test]
        public void DBConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DBConfig
            //Assert.IsInstanceOfType<DBConfig> (instance, "variable 'instance' is a DBConfig");
        }


        /// <summary>
        /// Test the property 'ConnectionString'
        /// </summary>
        [Test]
        public void ConnectionStringTest()
        {
            // TODO unit test for the property 'ConnectionString'
        }
        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Test]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
