/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetectionTypeEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetectionTypeEnumTests
    {
        // TODO uncomment below to declare an instance variable for DetectionTypeEnum
        //private DetectionTypeEnum instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetectionTypeEnum
            //instance = new DetectionTypeEnum();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetectionTypeEnum
        /// </summary>
        [Test]
        public void DetectionTypeEnumInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetectionTypeEnum
            //Assert.IsInstanceOfType<DetectionTypeEnum> (instance, "variable 'instance' is a DetectionTypeEnum");
        }



    }

}
