/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EHConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EHConfigTests
    {
        // TODO uncomment below to declare an instance variable for EHConfig
        //private EHConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EHConfig
            //instance = new EHConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EHConfig
        /// </summary>
        [Test]
        public void EHConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EHConfig
            //Assert.IsInstanceOfType<EHConfig> (instance, "variable 'instance' is a EHConfig");
        }


        /// <summary>
        /// Test the property 'ContainerValue'
        /// </summary>
        [Test]
        public void ContainerValueTest()
        {
            // TODO unit test for the property 'ContainerValue'
        }
        /// <summary>
        /// Test the property 'EhConnectionString'
        /// </summary>
        [Test]
        public void EhConnectionStringTest()
        {
            // TODO unit test for the property 'EhConnectionString'
        }
        /// <summary>
        /// Test the property 'EhKeyName'
        /// </summary>
        [Test]
        public void EhKeyNameTest()
        {
            // TODO unit test for the property 'EhKeyName'
        }
        /// <summary>
        /// Test the property 'EhKeyValue'
        /// </summary>
        [Test]
        public void EhKeyValueTest()
        {
            // TODO unit test for the property 'EhKeyValue'
        }
        /// <summary>
        /// Test the property 'EhName'
        /// </summary>
        [Test]
        public void EhNameTest()
        {
            // TODO unit test for the property 'EhName'
        }
        /// <summary>
        /// Test the property 'EhNamespace'
        /// </summary>
        [Test]
        public void EhNamespaceTest()
        {
            // TODO unit test for the property 'EhNamespace'
        }
        /// <summary>
        /// Test the property 'StorageAccountKeyValue'
        /// </summary>
        [Test]
        public void StorageAccountKeyValueTest()
        {
            // TODO unit test for the property 'StorageAccountKeyValue'
        }
        /// <summary>
        /// Test the property 'StorageAccountNameValue'
        /// </summary>
        [Test]
        public void StorageAccountNameValueTest()
        {
            // TODO unit test for the property 'StorageAccountNameValue'
        }

    }

}
