/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FieldTypeTransformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldTypeTransformationTests
    {
        // TODO uncomment below to declare an instance variable for FieldTypeTransformation
        //private FieldTypeTransformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldTypeTransformation
            //instance = new FieldTypeTransformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldTypeTransformation
        /// </summary>
        [Test]
        public void FieldTypeTransformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldTypeTransformation
            //Assert.IsInstanceOfType<FieldTypeTransformation> (instance, "variable 'instance' is a FieldTypeTransformation");
        }


        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Transformation'
        /// </summary>
        [Test]
        public void TransformationTest()
        {
            // TODO unit test for the property 'Transformation'
        }

    }

}
