/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FieldTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldTypesTests
    {
        // TODO uncomment below to declare an instance variable for FieldTypes
        //private FieldTypes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldTypes
            //instance = new FieldTypes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldTypes
        /// </summary>
        [Test]
        public void FieldTypesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldTypes
            //Assert.IsInstanceOfType<FieldTypes> (instance, "variable 'instance' is a FieldTypes");
        }


        /// <summary>
        /// Test the property 'MinScore'
        /// </summary>
        [Test]
        public void MinScoreTest()
        {
            // TODO unit test for the property 'MinScore'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
