/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FPEValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FPEValueTests
    {
        // TODO uncomment below to declare an instance variable for FPEValue
        //private FPEValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FPEValue
            //instance = new FPEValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FPEValue
        /// </summary>
        [Test]
        public void FPEValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FPEValue
            //Assert.IsInstanceOfType<FPEValue> (instance, "variable 'instance' is a FPEValue");
        }


        /// <summary>
        /// Test the property 'Decrypt'
        /// </summary>
        [Test]
        public void DecryptTest()
        {
            // TODO unit test for the property 'Decrypt'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Tweak'
        /// </summary>
        [Test]
        public void TweakTest()
        {
            // TODO unit test for the property 'Tweak'
        }

    }

}
