/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Graphic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GraphicTests
    {
        // TODO uncomment below to declare an instance variable for Graphic
        //private Graphic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Graphic
            //instance = new Graphic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Graphic
        /// </summary>
        [Test]
        public void GraphicInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Graphic
            //Assert.IsInstanceOfType<Graphic> (instance, "variable 'instance' is a Graphic");
        }


        /// <summary>
        /// Test the property 'FillColorValue'
        /// </summary>
        [Test]
        public void FillColorValueTest()
        {
            // TODO unit test for the property 'FillColorValue'
        }

    }

}
