/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KafkaConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KafkaConfigTests
    {
        // TODO uncomment below to declare an instance variable for KafkaConfig
        //private KafkaConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KafkaConfig
            //instance = new KafkaConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KafkaConfig
        /// </summary>
        [Test]
        public void KafkaConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KafkaConfig
            //Assert.IsInstanceOfType<KafkaConfig> (instance, "variable 'instance' is a KafkaConfig");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'SaslPassword'
        /// </summary>
        [Test]
        public void SaslPasswordTest()
        {
            // TODO unit test for the property 'SaslPassword'
        }
        /// <summary>
        /// Test the property 'SaslUsername'
        /// </summary>
        [Test]
        public void SaslUsernameTest()
        {
            // TODO unit test for the property 'SaslUsername'
        }
        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Test]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

    }

}
