/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PatternRecognizer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatternRecognizerTests
    {
        // TODO uncomment below to declare an instance variable for PatternRecognizer
        //private PatternRecognizer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatternRecognizer
            //instance = new PatternRecognizer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatternRecognizer
        /// </summary>
        [Test]
        public void PatternRecognizerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatternRecognizer
            //Assert.IsInstanceOfType<PatternRecognizer> (instance, "variable 'instance' is a PatternRecognizer");
        }


        /// <summary>
        /// Test the property 'Blacklist'
        /// </summary>
        [Test]
        public void BlacklistTest()
        {
            // TODO unit test for the property 'Blacklist'
        }
        /// <summary>
        /// Test the property 'ContextPhrases'
        /// </summary>
        [Test]
        public void ContextPhrasesTest()
        {
            // TODO unit test for the property 'ContextPhrases'
        }
        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Test]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Patterns'
        /// </summary>
        [Test]
        public void PatternsTest()
        {
            // TODO unit test for the property 'Patterns'
        }

    }

}
