/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing S3Config
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class S3ConfigTests
    {
        // TODO uncomment below to declare an instance variable for S3Config
        //private S3Config instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of S3Config
            //instance = new S3Config();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of S3Config
        /// </summary>
        [Test]
        public void S3ConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" S3Config
            //Assert.IsInstanceOfType<S3Config> (instance, "variable 'instance' is a S3Config");
        }


        /// <summary>
        /// Test the property 'AccessId'
        /// </summary>
        [Test]
        public void AccessIdTest()
        {
            // TODO unit test for the property 'AccessId'
        }
        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Test]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }
        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Test]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }
        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Test]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

    }

}
