/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScanRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScanRequestTests
    {
        // TODO uncomment below to declare an instance variable for ScanRequest
        //private ScanRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScanRequest
            //instance = new ScanRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScanRequest
        /// </summary>
        [Test]
        public void ScanRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScanRequest
            //Assert.IsInstanceOfType<ScanRequest> (instance, "variable 'instance' is a ScanRequest");
        }


        /// <summary>
        /// Test the property 'AnalyzeTemplate'
        /// </summary>
        [Test]
        public void AnalyzeTemplateTest()
        {
            // TODO unit test for the property 'AnalyzeTemplate'
        }
        /// <summary>
        /// Test the property 'AnonymizeTemplate'
        /// </summary>
        [Test]
        public void AnonymizeTemplateTest()
        {
            // TODO unit test for the property 'AnonymizeTemplate'
        }
        /// <summary>
        /// Test the property 'DatasinkTemplate'
        /// </summary>
        [Test]
        public void DatasinkTemplateTest()
        {
            // TODO unit test for the property 'DatasinkTemplate'
        }
        /// <summary>
        /// Test the property 'ScanTemplate'
        /// </summary>
        [Test]
        public void ScanTemplateTest()
        {
            // TODO unit test for the property 'ScanTemplate'
        }

    }

}
