/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Schedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduleTests
    {
        // TODO uncomment below to declare an instance variable for Schedule
        //private Schedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Schedule
            //instance = new Schedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Schedule
        /// </summary>
        [Test]
        public void ScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Schedule
            //Assert.IsInstanceOfType<Schedule> (instance, "variable 'instance' is a Schedule");
        }


        /// <summary>
        /// Test the property 'RecurrencePeriod'
        /// </summary>
        [Test]
        public void RecurrencePeriodTest()
        {
            // TODO unit test for the property 'RecurrencePeriod'
        }

    }

}
