/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Transformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransformationTests
    {
        // TODO uncomment below to declare an instance variable for Transformation
        //private Transformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transformation
            //instance = new Transformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transformation
        /// </summary>
        [Test]
        public void TransformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transformation
            //Assert.IsInstanceOfType<Transformation> (instance, "variable 'instance' is a Transformation");
        }


        /// <summary>
        /// Test the property 'FPEValue'
        /// </summary>
        [Test]
        public void FPEValueTest()
        {
            // TODO unit test for the property 'FPEValue'
        }
        /// <summary>
        /// Test the property 'HashValue'
        /// </summary>
        [Test]
        public void HashValueTest()
        {
            // TODO unit test for the property 'HashValue'
        }
        /// <summary>
        /// Test the property 'MaskValue'
        /// </summary>
        [Test]
        public void MaskValueTest()
        {
            // TODO unit test for the property 'MaskValue'
        }
        /// <summary>
        /// Test the property 'RedactValue'
        /// </summary>
        [Test]
        public void RedactValueTest()
        {
            // TODO unit test for the property 'RedactValue'
        }
        /// <summary>
        /// Test the property 'ReplaceValue'
        /// </summary>
        [Test]
        public void ReplaceValueTest()
        {
            // TODO unit test for the property 'ReplaceValue'
        }

    }

}
