/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AnonymizeTemplate represents the template definition of the Anonymize service for anonymizying the sensitive data
    /// </summary>
    [DataContract]
    public partial class AnonymizeTemplate :  IEquatable<AnonymizeTemplate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnonymizeTemplate" /> class.
        /// </summary>
        /// <param name="createTime">Template Creation date.</param>
        /// <param name="defaultTransformation">defaultTransformation.</param>
        /// <param name="description">Template description.</param>
        /// <param name="fieldTypeTransformations">FieldTypeTransformation represents the transformation for an array of fields types.</param>
        /// <param name="modifiedTime">Template modification date.</param>
        public AnonymizeTemplate(string createTime = default(string), Transformation defaultTransformation = default(Transformation), string description = default(string), List<FieldTypeTransformation> fieldTypeTransformations = default(List<FieldTypeTransformation>), string modifiedTime = default(string))
        {
            this.CreateTime = createTime;
            this.DefaultTransformation = defaultTransformation;
            this.Description = description;
            this.FieldTypeTransformations = fieldTypeTransformations;
            this.ModifiedTime = modifiedTime;
        }
        
        /// <summary>
        /// Template Creation date
        /// </summary>
        /// <value>Template Creation date</value>
        [DataMember(Name="createTime", EmitDefaultValue=false)]
        public string CreateTime { get; set; }

        /// <summary>
        /// Gets or Sets DefaultTransformation
        /// </summary>
        [DataMember(Name="defaultTransformation", EmitDefaultValue=false)]
        public Transformation DefaultTransformation { get; set; }

        /// <summary>
        /// Template description
        /// </summary>
        /// <value>Template description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// FieldTypeTransformation represents the transformation for an array of fields types
        /// </summary>
        /// <value>FieldTypeTransformation represents the transformation for an array of fields types</value>
        [DataMember(Name="fieldTypeTransformations", EmitDefaultValue=false)]
        public List<FieldTypeTransformation> FieldTypeTransformations { get; set; }

        /// <summary>
        /// Template modification date
        /// </summary>
        /// <value>Template modification date</value>
        [DataMember(Name="modifiedTime", EmitDefaultValue=false)]
        public string ModifiedTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnonymizeTemplate {\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  DefaultTransformation: ").Append(DefaultTransformation).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FieldTypeTransformations: ").Append(FieldTypeTransformations).Append("\n");
            sb.Append("  ModifiedTime: ").Append(ModifiedTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnonymizeTemplate);
        }

        /// <summary>
        /// Returns true if AnonymizeTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of AnonymizeTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnonymizeTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CreateTime == input.CreateTime ||
                    (this.CreateTime != null &&
                    this.CreateTime.Equals(input.CreateTime))
                ) && 
                (
                    this.DefaultTransformation == input.DefaultTransformation ||
                    (this.DefaultTransformation != null &&
                    this.DefaultTransformation.Equals(input.DefaultTransformation))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.FieldTypeTransformations == input.FieldTypeTransformations ||
                    this.FieldTypeTransformations != null &&
                    this.FieldTypeTransformations.SequenceEqual(input.FieldTypeTransformations)
                ) && 
                (
                    this.ModifiedTime == input.ModifiedTime ||
                    (this.ModifiedTime != null &&
                    this.ModifiedTime.Equals(input.ModifiedTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CreateTime != null)
                    hashCode = hashCode * 59 + this.CreateTime.GetHashCode();
                if (this.DefaultTransformation != null)
                    hashCode = hashCode * 59 + this.DefaultTransformation.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.FieldTypeTransformations != null)
                    hashCode = hashCode * 59 + this.FieldTypeTransformations.GetHashCode();
                if (this.ModifiedTime != null)
                    hashCode = hashCode * 59 + this.ModifiedTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
