/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Represents the cloud storage config - supported storage: Azure blob storage, AWS S3, Google storage
    /// </summary>
    [DataContract]
    public partial class CloudStorageConfig :  IEquatable<CloudStorageConfig>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CloudStorageConfig" /> class.
        /// </summary>
        /// <param name="googleStorageConfig">googleStorageConfig.</param>
        /// <param name="blobStorageConfig">blobStorageConfig.</param>
        /// <param name="s3Config">s3Config.</param>
        public CloudStorageConfig(GoogleStorageConfig googleStorageConfig = default(GoogleStorageConfig), BlobStorageConfig blobStorageConfig = default(BlobStorageConfig), S3Config s3Config = default(S3Config))
        {
            this.GoogleStorageConfig = googleStorageConfig;
            this.BlobStorageConfig = blobStorageConfig;
            this.S3Config = s3Config;
        }
        
        /// <summary>
        /// Gets or Sets GoogleStorageConfig
        /// </summary>
        [DataMember(Name="GoogleStorageConfig", EmitDefaultValue=false)]
        public GoogleStorageConfig GoogleStorageConfig { get; set; }

        /// <summary>
        /// Gets or Sets BlobStorageConfig
        /// </summary>
        [DataMember(Name="blobStorageConfig", EmitDefaultValue=false)]
        public BlobStorageConfig BlobStorageConfig { get; set; }

        /// <summary>
        /// Gets or Sets S3Config
        /// </summary>
        [DataMember(Name="s3Config", EmitDefaultValue=false)]
        public S3Config S3Config { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CloudStorageConfig {\n");
            sb.Append("  GoogleStorageConfig: ").Append(GoogleStorageConfig).Append("\n");
            sb.Append("  BlobStorageConfig: ").Append(BlobStorageConfig).Append("\n");
            sb.Append("  S3Config: ").Append(S3Config).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CloudStorageConfig);
        }

        /// <summary>
        /// Returns true if CloudStorageConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of CloudStorageConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CloudStorageConfig input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GoogleStorageConfig == input.GoogleStorageConfig ||
                    (this.GoogleStorageConfig != null &&
                    this.GoogleStorageConfig.Equals(input.GoogleStorageConfig))
                ) && 
                (
                    this.BlobStorageConfig == input.BlobStorageConfig ||
                    (this.BlobStorageConfig != null &&
                    this.BlobStorageConfig.Equals(input.BlobStorageConfig))
                ) && 
                (
                    this.S3Config == input.S3Config ||
                    (this.S3Config != null &&
                    this.S3Config.Equals(input.S3Config))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GoogleStorageConfig != null)
                    hashCode = hashCode * 59 + this.GoogleStorageConfig.GetHashCode();
                if (this.BlobStorageConfig != null)
                    hashCode = hashCode * 59 + this.BlobStorageConfig.GetHashCode();
                if (this.S3Config != null)
                    hashCode = hashCode * 59 + this.S3Config.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
