/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DatasinkTemplate
    /// </summary>
    [DataContract]
    public partial class DatasinkTemplate :  IEquatable<DatasinkTemplate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatasinkTemplate" /> class.
        /// </summary>
        /// <param name="analyzeDatasink">Datasink represents the configuration for storing the scanner output. Datasink can output both of the analyze and anonymize results and to multiple outputs Supported outputs are CloudStorage: AWS S3, Azure Blob storage, Google Storage Streams: Azure EventHub, Kafka Database: MySql, SqlLite3, MSSQL, PostgreSQL.</param>
        /// <param name="anonymizeDatasink">anonymizeDatasink.</param>
        /// <param name="description">Template description.</param>
        public DatasinkTemplate(List<Datasink> analyzeDatasink = default(List<Datasink>), List<Datasink> anonymizeDatasink = default(List<Datasink>), string description = default(string))
        {
            this.AnalyzeDatasink = analyzeDatasink;
            this.AnonymizeDatasink = anonymizeDatasink;
            this.Description = description;
        }
        
        /// <summary>
        /// Datasink represents the configuration for storing the scanner output. Datasink can output both of the analyze and anonymize results and to multiple outputs Supported outputs are CloudStorage: AWS S3, Azure Blob storage, Google Storage Streams: Azure EventHub, Kafka Database: MySql, SqlLite3, MSSQL, PostgreSQL
        /// </summary>
        /// <value>Datasink represents the configuration for storing the scanner output. Datasink can output both of the analyze and anonymize results and to multiple outputs Supported outputs are CloudStorage: AWS S3, Azure Blob storage, Google Storage Streams: Azure EventHub, Kafka Database: MySql, SqlLite3, MSSQL, PostgreSQL</value>
        [DataMember(Name="analyzeDatasink", EmitDefaultValue=false)]
        public List<Datasink> AnalyzeDatasink { get; set; }

        /// <summary>
        /// Gets or Sets AnonymizeDatasink
        /// </summary>
        [DataMember(Name="anonymizeDatasink", EmitDefaultValue=false)]
        public List<Datasink> AnonymizeDatasink { get; set; }

        /// <summary>
        /// Template description
        /// </summary>
        /// <value>Template description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DatasinkTemplate {\n");
            sb.Append("  AnalyzeDatasink: ").Append(AnalyzeDatasink).Append("\n");
            sb.Append("  AnonymizeDatasink: ").Append(AnonymizeDatasink).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DatasinkTemplate);
        }

        /// <summary>
        /// Returns true if DatasinkTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of DatasinkTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatasinkTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AnalyzeDatasink == input.AnalyzeDatasink ||
                    this.AnalyzeDatasink != null &&
                    this.AnalyzeDatasink.SequenceEqual(input.AnalyzeDatasink)
                ) && 
                (
                    this.AnonymizeDatasink == input.AnonymizeDatasink ||
                    this.AnonymizeDatasink != null &&
                    this.AnonymizeDatasink.SequenceEqual(input.AnonymizeDatasink)
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AnalyzeDatasink != null)
                    hashCode = hashCode * 59 + this.AnalyzeDatasink.GetHashCode();
                if (this.AnonymizeDatasink != null)
                    hashCode = hashCode * 59 + this.AnonymizeDatasink.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
