/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FieldTypeGraphic represents the graphics for an array of fields types
    /// </summary>
    [DataContract]
    public partial class FieldTypeGraphic :  IEquatable<FieldTypeGraphic>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldTypeGraphic" /> class.
        /// </summary>
        /// <param name="fields">The array of field types.</param>
        /// <param name="graphic">graphic.</param>
        public FieldTypeGraphic(List<FieldTypes> fields = default(List<FieldTypes>), Graphic graphic = default(Graphic))
        {
            this.Fields = fields;
            this.Graphic = graphic;
        }
        
        /// <summary>
        /// The array of field types
        /// </summary>
        /// <value>The array of field types</value>
        [DataMember(Name="fields", EmitDefaultValue=false)]
        public List<FieldTypes> Fields { get; set; }

        /// <summary>
        /// Gets or Sets Graphic
        /// </summary>
        [DataMember(Name="graphic", EmitDefaultValue=false)]
        public Graphic Graphic { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FieldTypeGraphic {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  Graphic: ").Append(Graphic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FieldTypeGraphic);
        }

        /// <summary>
        /// Returns true if FieldTypeGraphic instances are equal
        /// </summary>
        /// <param name="input">Instance of FieldTypeGraphic to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FieldTypeGraphic input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Fields == input.Fields ||
                    this.Fields != null &&
                    this.Fields.SequenceEqual(input.Fields)
                ) && 
                (
                    this.Graphic == input.Graphic ||
                    (this.Graphic != null &&
                    this.Graphic.Equals(input.Graphic))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Fields != null)
                    hashCode = hashCode * 59 + this.Fields.GetHashCode();
                if (this.Graphic != null)
                    hashCode = hashCode * 59 + this.Graphic.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
