/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Fill the bbox with a color
    /// </summary>
    [DataContract]
    public partial class FillColorValue :  IEquatable<FillColorValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FillColorValue" /> class.
        /// </summary>
        /// <param name="blue">0 - 255.</param>
        /// <param name="green">0 - 255.</param>
        /// <param name="red">0 - 255.</param>
        public FillColorValue(double? blue = default(double?), double? green = default(double?), double? red = default(double?))
        {
            this.Blue = blue;
            this.Green = green;
            this.Red = red;
        }
        
        /// <summary>
        /// 0 - 255
        /// </summary>
        /// <value>0 - 255</value>
        [DataMember(Name="blue", EmitDefaultValue=false)]
        public double? Blue { get; set; }

        /// <summary>
        /// 0 - 255
        /// </summary>
        /// <value>0 - 255</value>
        [DataMember(Name="green", EmitDefaultValue=false)]
        public double? Green { get; set; }

        /// <summary>
        /// 0 - 255
        /// </summary>
        /// <value>0 - 255</value>
        [DataMember(Name="red", EmitDefaultValue=false)]
        public double? Red { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FillColorValue {\n");
            sb.Append("  Blue: ").Append(Blue).Append("\n");
            sb.Append("  Green: ").Append(Green).Append("\n");
            sb.Append("  Red: ").Append(Red).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FillColorValue);
        }

        /// <summary>
        /// Returns true if FillColorValue instances are equal
        /// </summary>
        /// <param name="input">Instance of FillColorValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FillColorValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Blue == input.Blue ||
                    (this.Blue != null &&
                    this.Blue.Equals(input.Blue))
                ) && 
                (
                    this.Green == input.Green ||
                    (this.Green != null &&
                    this.Green.Equals(input.Green))
                ) && 
                (
                    this.Red == input.Red ||
                    (this.Red != null &&
                    this.Red.Equals(input.Red))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Blue != null)
                    hashCode = hashCode * 59 + this.Blue.GetHashCode();
                if (this.Green != null)
                    hashCode = hashCode * 59 + this.Green.GetHashCode();
                if (this.Red != null)
                    hashCode = hashCode * 59 + this.Red.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
