/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Graphic represents how the sensitive content will be transforms
    /// </summary>
    [DataContract]
    public partial class Graphic :  IEquatable<Graphic>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Graphic" /> class.
        /// </summary>
        /// <param name="fillColorValue">fillColorValue.</param>
        public Graphic(FillColorValue fillColorValue = default(FillColorValue))
        {
            this.FillColorValue = fillColorValue;
        }
        
        /// <summary>
        /// Gets or Sets FillColorValue
        /// </summary>
        [DataMember(Name="fillColorValue", EmitDefaultValue=false)]
        public FillColorValue FillColorValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Graphic {\n");
            sb.Append("  FillColorValue: ").Append(FillColorValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Graphic);
        }

        /// <summary>
        /// Returns true if Graphic instances are equal
        /// </summary>
        /// <param name="input">Instance of Graphic to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Graphic input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FillColorValue == input.FillColorValue ||
                    (this.FillColorValue != null &&
                    this.FillColorValue.Equals(input.FillColorValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FillColorValue != null)
                    hashCode = hashCode * 59 + this.FillColorValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
