/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// And sending the output to the selected destination
    /// </summary>
    [DataContract]
    public partial class ScanTemplate :  IEquatable<ScanTemplate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScanTemplate" /> class.
        /// </summary>
        /// <param name="cloudStorageConfig">cloudStorageConfig.</param>
        /// <param name="description">Template description.</param>
        public ScanTemplate(CloudStorageConfig cloudStorageConfig = default(CloudStorageConfig), string description = default(string))
        {
            this.CloudStorageConfig = cloudStorageConfig;
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets CloudStorageConfig
        /// </summary>
        [DataMember(Name="cloudStorageConfig", EmitDefaultValue=false)]
        public CloudStorageConfig CloudStorageConfig { get; set; }

        /// <summary>
        /// Template description
        /// </summary>
        /// <value>Template description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScanTemplate {\n");
            sb.Append("  CloudStorageConfig: ").Append(CloudStorageConfig).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScanTemplate);
        }

        /// <summary>
        /// Returns true if ScanTemplate instances are equal
        /// </summary>
        /// <param name="input">Instance of ScanTemplate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScanTemplate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CloudStorageConfig == input.CloudStorageConfig ||
                    (this.CloudStorageConfig != null &&
                    this.CloudStorageConfig.Equals(input.CloudStorageConfig))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CloudStorageConfig != null)
                    hashCode = hashCode * 59 + this.CloudStorageConfig.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
