/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnonymizeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AnonymizeApiTests
    {
        private AnonymizeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnonymizeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnonymizeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AnonymizeApi
            //Assert.IsInstanceOfType(typeof(AnonymizeApi), instance, "instance is a AnonymizeApi");
        }

        
        /// <summary>
        /// Test AnonymizeRequest
        /// </summary>
        [Test]
        public void AnonymizeRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? projectId = null;
            //AnonymizeRequest body = null;
            //var response = instance.AnonymizeRequest(projectId, body);
            //Assert.IsInstanceOf<AnonymizeResponse> (response, "response is AnonymizeResponse");
        }
        
        /// <summary>
        /// Test DeleteAnonymizeTemplateRequest
        /// </summary>
        [Test]
        public void DeleteAnonymizeTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //instance.DeleteAnonymizeTemplateRequest(projectId, templateId);
            
        }
        
        /// <summary>
        /// Test GetAnonymizeTemplateRequest
        /// </summary>
        [Test]
        public void GetAnonymizeTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //instance.GetAnonymizeTemplateRequest(projectId, templateId);
            
        }
        
        /// <summary>
        /// Test PostAnonymizeTemplateRequest
        /// </summary>
        [Test]
        public void PostAnonymizeTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //AnonymizeTemplate body = null;
            //instance.PostAnonymizeTemplateRequest(projectId, templateId, body);
            
        }
        
        /// <summary>
        /// Test PutAnonymizeTemplateRequest
        /// </summary>
        [Test]
        public void PutAnonymizeTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //AnonymizeTemplate body = null;
            //instance.PutAnonymizeTemplateRequest(projectId, templateId, body);
            
        }
        
    }

}
