/* 
 * Presidio.
 *
 * Documentation for Presidio API Swagger.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DatasinkApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DatasinkApiTests
    {
        private DatasinkApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DatasinkApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DatasinkApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DatasinkApi
            //Assert.IsInstanceOfType(typeof(DatasinkApi), instance, "instance is a DatasinkApi");
        }

        
        /// <summary>
        /// Test DeleteDatasinkTemplateRequest
        /// </summary>
        [Test]
        public void DeleteDatasinkTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //instance.DeleteDatasinkTemplateRequest(projectId, templateId);
            
        }
        
        /// <summary>
        /// Test GetDatasinkTemplateRequest
        /// </summary>
        [Test]
        public void GetDatasinkTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //instance.GetDatasinkTemplateRequest(projectId, templateId);
            
        }
        
        /// <summary>
        /// Test PostDatasinkTemplateRequest
        /// </summary>
        [Test]
        public void PostDatasinkTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //DatasinkTemplate body = null;
            //instance.PostDatasinkTemplateRequest(projectId, templateId, body);
            
        }
        
        /// <summary>
        /// Test PutDatasinkTemplateRequest
        /// </summary>
        [Test]
        public void PutDatasinkTemplateRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectId = null;
            //string templateId = null;
            //DatasinkTemplate body = null;
            //instance.PutDatasinkTemplateRequest(projectId, templateId, body);
            
        }
        
    }

}
